### ISSUE TITLE
Ammo and medic bags in wrong slot

### ISSUE THREAD

**Issue by kaloczikvn** [kaloczikvn/kPM#29]
See Randomizer mod for better solution

**Comment by Simber1** [comment]
I create a table containing all the the players weapons called weapons then compare `Weapons[3].name:match("/U_.+"):sub(4)` to bagTable `self.bagsTable = {"Medkit","Ammobag"}` . If it returns true the bag goes in WeaponSlot.WeaponSlot_4, if not their gadget goes in WeaponSlot.WeaponSlot_3.   
  
https://github.com/Simber1/VU-Randomizer/blob/eac67e07bfdc480eed525b521cf1e853325d1998/ext/server/__init__.lua#L125

**Comment by kaloczikvn** [comment]
Fixed in 281f7ae073e44d264ce85b9d363c2f39cf3d6388
