### ISSUE TITLE
Can't respawn after dying in warmup without changing team or class

### ISSUE THREAD

**Issue by Simber1** [kaloczikvn/kPM#36]
If you manage to die in warmup, either through deserting or suicide you don't respawn naturally.

**Comment by Simber1** [comment]
Could just have an event that is subbed to on warmup start and deleted on game start that loops through the players every second or 2 and respawns them if they are dead.

**Comment by kaloczikvn** [comment]
Fixed in c8118aec63e49a20e065adacadc7c781233842a5
