### ISSUE TITLE
Team mix-up bug

### ISSUE THREAD

**Issue by turbopasi** [kaloczikvn/kPM#51]
It occurs on a regular basis that one can end up on the wrong side , like an imposter. In the scoreboard he is listed as "Attacker" but spawns in the Defender Team, and Defender Spawn. So he can't defuse the bomb. On the other hand  he can be listed as "Defender" but spawns in the Attacker Team, can't plant the bomb. 

I can't really tell why and when this is happening , but it happens ... a lot ! 
Just wanted to dump this here.

**Comment by kaloczikvn** [comment]
You might wanna update to the latest version of promod, i cant seem to reproduce the bug.

**Comment by turbopasi** [comment]
If i am not mistaken we are running the latest release of promod already (`tag 0.8`) . For what I know, after server restart , everything is back to normal. It often occurs when the client crashes and then rejoins the server on another team than he was before. Are you planning a new release ?

**Comment by turbopasi** [comment]
We had an idea that this issue might come from the server's auto-balance feature. We try it and see if something comes up.

**Comment by kaloczikvn** [comment]
Is it still an issue? Latest version works perfectly for me.

**Comment by turbopasi** [comment]
If it is it's probably not related to kPM, since it already works perfect on your end. I guess we can close this :)
